version: '3.5'

services:
  # app:
  #  container_name: nest-app
  #  build:
  #    context: .
  #    dockerfile: Dockerfile
  #  ports:
  #    - '3000:3000'
  #  depends_on:
  #    - db
  #  env_file:
  #   - .env
  #  volumes:
  #    - ./src:/app/
  db:
    image: postgres:14.1-alpine
    restart: always
    # environment:
    #   - POSTGRES_USER=postgres
    #   - POSTGRES_PASSWORD=Rasul1234
    container_name: test
    volumes:
      - ./db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - '5432:5432'
  # pgadmin:
  #   image: dpage/pgadmin4
  #   restart: always
  #   container_name: nest-pgadmin4
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@admin.com
  #     - PGADMIN_DEFAULT_PASSWORD=pgadmin4
  #   ports:
  #     - '5050:80'
  #   depends_on:
  #     - db
  